trigger:
  - main  # Set the branch you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install dbt
      dbt run
    displayName: 'Run dbt'