trigger:
- main

schedules:
- cron: '*/5 * * * *'
  branches:
    include:
    - main

jobs:
- job: RunDbtModels
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install dbt
      pip install dbt-snowflake
    displayName: 'Install dbt and dependencies'

  - script: |
      python -m dbt deps --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Install dbt dependencies'

  - script: |
      python -m dbt run --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Run dbt models'

  - script: |
      python -m dbt test --profiles-dir $(Build.Repository.LocalPath)/dfz --project-dir $(Build.Repository.LocalPath)/dfz
    displayName: 'Run dbt tests'
